version: '3.8'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  postgres_keycloak:
    image: postgres:14.3
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
    ports:
      - "${KEYCLOAK_DB_PORT}:5432"
    volumes:
      - ./postgres_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_FEATURES: "${KEYCLOAK_FEATURES}"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
      - --features=${KEYCLOAK_FEATURES}

