version: '3.8'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres
    environment:
      POSTGRES_USER: copuser
      POSTGRES_PASSWORD: coppass
      POSTGRES_DB: copdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  postgres_keycloak:
    image: postgres:14.3
    container_name: postgres_keycloak
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_keycloak:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_FEATURES: "scripts,preview"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    command:
      - start-dev
      - --import-realm
      - --features=scripts,preview

